[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = "0.8.25"

remappings = [
    "forge-std/=lib/rain.interpreter/lib/rain.interpreter.interface/lib/forge-std/src/",
    "rain.sol.codegen/=lib/rain.interpreter/lib/rain.interpreter.interface/lib/rain.sol.codegen/src/",
    "rain.intorastring/=lib/rain.interpreter/lib/rain.interpreter.interface/lib/rain.intorastring/src/",
    "rain.metadata/=lib/rain.metadata/src/",
    "rain.interpreter/=lib/rain.interpreter/src/",
    "@openzeppelin/contracts/token/ERC20/=lib/rain.interpreter/lib/rain.interpreter.interface/lib/forge-std/src/interfaces/",
]

fs_permissions = [
    { access = "read-write", path = "src/generated" },
    { access = "read-write", path = "meta" },
    { access = "read", path = "lib/rain.interpreter/meta/RainterpreterExpressionDeployerNPE2.rain.meta" },
]

optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false