[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = "0.8.25"

remappings = [
    "rain.interpreter/=lib/rain.interpreter/src/",
    "@openzeppelin/=lib/rain.interpreter/lib/openzeppelin-contracts/",
    "rain.intorastring/=lib/rain.interpreter/lib/rain.intorastring/",
    "rain.metadata/=lib/rain.interpreter/lib/rain.metadata/src/",
    "rain.interpreter.interface/=lib/rain.interpreter/lib/rain.interpreter.interface/src/",
]

fs_permissions = [
    { access = "read", path = "lib/rain.interpreter/meta/RainterpreterExpressionDeployerNPE2.rain.meta" },
    { access = "write", path = "meta/FlareFtsoSubParserAuthoringMeta.rain.meta" },
    { access = "read", path = "meta/FlareFtsoSubParserDescribedByMetaV1.rain.meta" },
]

optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false