name: Manual sol artifacts
on:
  workflow_dispatch:
    inputs:
      suite:
        description: "The suite to deploy"
        required: true
        type: choice
        options:
          - flare-ftso-words
jobs:
  deploy:
    uses: rainlanguage/rainix/.github/workflows/rainix-manual-sol-artifacts.yaml@6b43e604e1b6ce3c00ece4ae159bb5d1457548b5
    with:
      suite: ${{ inputs.suite }}
    secrets: inherit
