name: Manual sol artifacts
on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to deploy to'
        required: true
        type: choice
        options:
          - songbird

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRIVATE_KEY || secrets.PRIVATE_KEY_DEV }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix run .#rainix-sol-prelude
        working-directory: ./lib/rain.interpreter
      - run: nix run .#rainix-rs-prelude
        working-directory: ./lib/rain.interpreter
      - run: nix run .#i9r-prelude
        working-directory: ./lib/rain.interpreter

      - run: nix run .#rainix-sol-prelude
      - run: nix run .#rainix-sol-artifacts
        env:
          ETH_RPC_URL: ${{ inputs.network == 'songbird' && secrets.CI_DEPLOY_SONGBIRD_RPC_URL || secrets.CI_DEPLOY_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.EXPLORER_VERIFICATION_KEY }}